services:
  mader_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ../.env
    ports:
      - "5432:5432"
  
  mader:
    image: mader
    entrypoint: ./infra/entrypoint.sh # isso é dentro do container, relativo ao WORKDIR
    build:
        context: ../. # isso define o contexto do build como a raiz do projeto
        dockerfile: ./infra/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mader_database
    env_file: # isso é fora do container, na raiz do projeto
      - ../.env

volumes:
  pgdata: