services:
  mader_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U your-postgres-user -d your-postgres-db"]
      interval: 2s
      timeout: 5s
      retries: 15
  
  mader:
    image: mader
    entrypoint: ./infra/entrypoint.sh # isso é dentro do container, relativo ao WORKDIR
    build:
        context: ../. # isso define o contexto do build como a raiz do projeto
        dockerfile: ./infra/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      mader_database:
        condition: service_healthy
      otel:
        condition: service_started
    env_file: # isso é fora do container, na raiz do projeto
      - ../.env

  otel:
    image: grafana/otel-lgtm
    ports:
      - "3000:3000"
      - "4317:4317"
    env_file:
      - ../.env
    
volumes:
  pgdata: